import { Product } from "@/types/product";
const shopData: Product[] = [
  {
    name: "Havit HV-G69 USB Gamepad",
    price: 2900, // 29.00 in cents
    id: "1",
    stock: 10,
    weight: 200,
    isActive: true,
    slug: "havit-hv-g69-usb-gamepad",
    imageUrl: "/images/products/product-1-bg-1.png",
  },
  {
    name: "iPhone 14 Plus , 6/128GB",
    price: 9900, // 99.00 in cents
    id: "2",
    stock: 5,
    weight: 500,
    isActive: true,
    slug: "iphone-14-plus-6-128gb",
    imageUrl: "/images/products/product-2-bg-1.png",
  },
  {
    name: "Apple iMac M1 24-inch 2021",
    price: 2900,
    id: "3",
    stock: 8,
    weight: 4500,
    isActive: true,
    slug: "apple-imac-m1-24-inch-2021",
    imageUrl: "/images/products/product-3-bg-1.png",
  },
  {
    name: "MacBook Air M1 chip, 8/256GB",
    price: 2900,
    id: "4",
    stock: 12,
    weight: 1200,
    isActive: true,
    slug: "macbook-air-m1-chip-8-256gb",
    imageUrl: "/images/products/product-4-bg-1.png",
  },
  {
    name: "Apple Watch Ultra",
    price: 2900,
    id: "5",
    stock: 15,
    weight: 300,
    isActive: true,
    slug: "apple-watch-ultra",
    imageUrl: "/images/products/product-5-bg-1.png",
  },
  {
    name: "Logitech MX Master 3 Mouse",
    price: 2900,
    id: "6",
    stock: 25,
    weight: 150,
    isActive: true,
    slug: "logitech-mx-master-3-mouse",
    imageUrl: "/images/products/product-6-bg-1.png",
  },
  {
    name: "Apple iPad Air 5th Gen - 64GB",
    price: 2900,
    id: "7",
    stock: 7,
    weight: 500,
    isActive: true,
    slug: "apple-ipad-air-5th-gen-64gb",
    imageUrl: "/images/products/product-7-bg-1.png",
  },
  {
    name: "Asus RT Dual Band Router",
    price: 2900,
    id: "8",
    stock: 18,
    weight: 400,
    isActive: true,
    slug: "asus-rt-dual-band-router",
    imageUrl: "/images/products/product-8-bg-1.png",
  },
];

export default shopData;
